---
title: "ORGANIZE"
output:
  html_document:
    toc: true
    toc_float: true
---

# **DONOR RECRUITMENT**

Here's a handy <a href="docs/liability_flowchart.pdf" target="_blank">**LIABILITY FLOW CHART** </a> to assuage donor's fears regarding liability. For more info check out our section on [liability](https://davisnightmarket.github.io/diy/legal#liability) 

Emails:
Make a database of all possible donors, classified them according likelihood to have leftovers, closing time and distance to your Night Market spot
link in our website or social pages to show legitimacy 
Personally
Connections

# **VOLUNTEER RECRUITMENT**

Methods of recruitment 
Signing up on a signup sheet at Night Market
At the market there is a table which contains a sign up binder and a sign  with lights saying sign up here 
Messages of interest on Social media ( Facebook and Instransgram) 
Messages of interest on a future website 
Volutenter recruitment fillers 
Post example 
Task for Volunteers 
Pick ups 
The first pick up the volutenter will do is with an established team member 
 Two reasons 
We can ensure that they show up 
They can watch an establish person perform the pick up   
Setting up the market 
 Volutenter  
Building bike trailer 
Building bike trailer is an ideal task for volutner in addition to a great recruit new volunteer 
Opening New day
Opening a requires enough volutenter to run every task 
Ie for Davis NIght market we need a minimum of people four to operate so each additional day we need a minimum of four new volunteers  

